.gitignore
.npmignore
README.md
demo/demo.jsx
demo/index.html
package.json
prepublish.sh
src/Button.jsx
src/ButtonGroup.jsx
src/ProcessingIndicator.jsx
src/ProgressBar.jsx
test/ButtonGroupSpec.jsx
test/ButtonSpec.jsx
test/ProcessingIndicatorSpec.jsx
test/ProgressBarSpec.jsx

Above are the files that will be included in the node module via <code>npm install canon-react</code>, dist contains the min version of canon-react and demo contains all the files needed for index.html to display properly (using components defined in canon-react.min.js). 
How to use:
Install via <code>npm install canon-react</code>
Where you would like to use react components from canon-react, add <code>var componentName = require('canon-react').componentName;</code>

[READY] NPM Module

---

demo/DemoActionMenu.jsx
demo/DemoDropdownSection.jsx
demo/DemoPrimaryDropdown.jsx
demo/DemoUtilityDropdown.jsx
demo/DemoView.jsx
src/Divider.jsx
src/Dropdown.jsx
src/DropdownItem.jsx
src/DropdownTrigger.jsx
src/Popover.jsx
src/index.js
test/DividerSpec.jsx
test/DropdownItemSpec.jsx
test/DropdownSpec.jsx
test/DropdownTriggerSpec.jsx
test/PopoverFooterSpec.jsx

this PR address https://github.com/rackerlabs/canon-react/issues/15

Action menu

---

CHANGELOG.md
README.md
package.json

Adds dropdowns and action buttons.

release v 0.4.0

---

.eslintrc
Gruntfile.js
package.json
src/ButtonGroup.jsx
src/Popover.jsx
src/PopoverBody.jsx
src/PopoverFooter.jsx
src/PopoverOverlay.jsx
src/ProgressBar.jsx
src/StatusIndicator.jsx
test/ProcessingIndicatorSpec.jsx

- added eslint to package.json
- fixed all eslint warnings

fix eslint warnings

---

CHANGELOG.md
package.json

Release version 0.6.1
1. Hide dropdowns when dropdown items are clicked
2. Fix bad prop types where children and className were misused
3. Add contributing guide and scripts for setup and development

chore(release): v 0.6.1

---

demo/DemoButtonSection.jsx
scripts/server
scripts/setup
scripts/update

Added a demo-build script. Fixed a typo on the demo page. Fixed a typo in the server script.

Added a demo-build script.

---

CHANGELOG.md
package.json

Fix some issues on the teether library

Upgrade tether

---

package.json
src/Button.jsx
src/ButtonGroup.jsx
src/Criteria.jsx
src/Dropdown.jsx
src/DropdownItem.jsx
src/Facet.jsx
src/FacetsSection.jsx
src/PopoverBody.jsx
src/PopoverFooter.jsx
src/PopoverOverlay.jsx
src/ProcessingIndicator.jsx
src/ProgressBar.jsx
src/StatusIndicator.jsx

implement #69 use classnames module to construct react classnames

---

CHANGELOG.md
package.json

Release version 0.6.4
1. Facets!
2. eslint upgrade
3. Karma upgrade

chore(release): v 0.6.4

---

CHANGELOG.md
package.json

Release  0.7.0
1. Facets!
2. eslint upgrade
3. Karma upgrade

chore(release): v 0.7.0

---

demo/DemoPopoverSection.jsx
src/StatusIndicator.jsx
test/StatusIndicatorSpec.jsx

Updates the  `StatusIndicator` element to render a `<span>` instead of a `<statusindicator>` .
Also fixed the popovers in the demo popover section.
This fixes issue #65

fix(StatusIndicator): Fix Status Indicator HTML

---

CHANGELOG.md
package.json

Release v 0.7.1
1. Fix StatusIndicator so it renders the proper element
2. Fix popovers in demo popover section

chore(release): v 0.7.1

---

CHANGELOG.md
package.json

1. Fix facets so they do not mutate the passed in selected criteria property

chore(release): v 0.7.2

---

demo/DemoPopover.jsx
demo/DemoPopoverSection.jsx
src/Popover.jsx
src/PopoverBackground.jsx
test/PopoverBackgroundSpec.jsx
test/PopoverSpec.jsx

Adds a background color for modal popovers when `isModal` property is truthy

Add modal option for popovers

---

.eslintrc
Gruntfile.js
demo/DemoPopoverSection.jsx
demo/demo.jsx
demo/index.html
karma.ci.js
karma.dev.js
package.json
src/DropdownTrigger.jsx
src/Popover.jsx
src/TooltipTrigger.jsx
test/ButtonGroupSpec.jsx
test/ButtonSpec.jsx
test/CriteriaSpec.jsx
test/DividerSpec.jsx
test/DropdownItemSpec.jsx
test/DropdownSpec.jsx
test/DropdownTriggerSpec.jsx
test/FacetSpec.jsx
test/FacetTogglerSpec.jsx
test/FacetsSectionSpec.jsx
test/PopoverBackgroundSpec.jsx
test/PopoverBodySpec.jsx
test/PopoverFooterSpec.jsx
test/PopoverOverlaySpec.jsx
test/PopoverSpec.jsx
test/ProcessingIndicatorSpec.jsx
test/ProgressBarSpec.jsx
test/StatusIndicatorSpec.jsx
test/TooltipTriggerSpec.jsx

This merges the PRs #87 and #66

chore: upgrade react version

---

CHANGELOG.md
package.json

Release v 0.9.1
1. Fix Facets for IE

chore(release): v 0.9.1

---

CHANGELOG.md
package.json

1. Added 'DetailList', 'DetailItem', 'DetailItemValue', and 'DetailItemKey' components.

chore(release): v 0.12.0

---

demo/DemoDetailSectionCollapsible.jsx
demo/DemoDetailSectionDefaultCollapsed.jsx
demo/DemoView.jsx
src/DetailsSection.jsx
src/index.js
test/DetailListSpec.jsx
test/DetailsSectionSpec.jsx

Added property to DetailsSection component isCollapsible,
which when passed true makes the section collapsible.

feat(details-section):allow collapsibility

---

CHANGELOG.md
package.json

1. Added 'Form', 'FormField', and related components to encapsulate Canon forms and form validation messages.
2. Added new props to the `DetailsSection` to make the section collapsible and more customizable.

chore(release): v 0.13.0

---

CHANGELOG.md
package.json

1. allow the horizontal layout of a form to be configurable.
2. export form components.

chore(release): v 0.13.1

---

demo/DemoPopoverSection.jsx
src/TooltipTrigger.jsx

fixes https://github.com/rackerlabs/canon-react/issues/116
had to add the demo fix as part of this since I couldn't run it locally to check
--
ps.: this is my first PR in this project, feel free to let me know how terribly I might have botched contribution guidelines : )

fix(tooltip): tooltip missing context from parent

---

src/DetailsSection.jsx
test/DetailsSectionSpec.jsx

fix(DetailsSection): fixes close section on body click

---

CHANGELOG.md
package.json

1. Fix rendering of error messages in form popover footer.
2. Fix collapsible sections so collapsing is only toggled on section header click.
3. Pass context to dropdown component.

chore(release): v 0.13.3

---

scripts/create_release_branch.py

Automates the creation of a new release pull request. Follow-up pull request will add a second script to call the GitHub API and create the release with relevant attachments.

feat(automation): add a script to automatically generate release branches

---

src/ButtonGroup.jsx
src/DetailItem.jsx
src/DetailItemKey.jsx
src/DetailItemValue.jsx
src/DetailList.jsx
src/DetailsSectionSubtitle.jsx
src/DetailsSectionTitle.jsx
src/Divider.jsx
src/ErrorIndicator.jsx
test/ButtonGroupSpec.jsx
test/DetailItemKeySpec.jsx
test/DetailItemSpec.jsx
test/DetailItemValueSpec.jsx
test/DetailListSpec.jsx
test/DetailsSectionSpec.jsx
test/DetailsSectionSubtitleSpec.jsx
test/DetailsSectionTitleSpec.jsx
test/DividerSpec.jsx
test/ErrorIndicatorSpec.jsx

This PR is one of a series to migrate some of our simple components within this library to stateless functional components.

refactor - migrate simple components to stateless functional components [ready]

---

README.md
scripts/publish_new_release.py

Also updated documentation. I'm leaving it in three parts deliberately, since each step requires different permissions.

feat(automation): add a script to automatically create a new release

---

CHANGELOG.md
package.json

1. Fix form popover target PropType
2. Add optional additional controls to form popover
3. Allow inline validation on form fields

chore(release): v 0.13.4

---

CHANGELOG.md
package.json

1. Adding list table components

chore(release): v 0.14.0

---

demo/DemoButtonGroupSection.jsx
demo/DemoButtonSection.jsx
demo/DemoDropdownSection.jsx
demo/DemoFacetsSection.jsx
demo/DemoListTableSection.jsx
demo/DemoPopoverSection.jsx
demo/DemoProgressBarSection.jsx
demo/DemoStatusIndicatorSection.jsx
demo/DemoTooltipSection.jsx

Update the demo components that display in a section to use the DetailsSection component
instead of wrapping in dovs with the rs-detail-section class. This should make the demos
update if/when the DetailsSection component is updated.

style(demo): Use DetailsSection in demos, instead of divs with rs-detail-section

---

CHANGELOG.md
package.json

1. Fix proptypes on table components.

chore(release): v 0.14.1

---

CHANGELOG.md
package.json

1. Fixed missing React import on table components.

chore(release): v 0.14.2

---

CHANGELOG.md
package.json

1. Added optional onShow prop to TooltipTrigger to enable tooltip tracking.

chore(release): v 0.14.3

---

.babelrc
.eslintrc
package.json
src/DropdownItem.jsx
test/DropdownItemSpec.jsx

otherwise you can't have dropdownitems that actually have links :relaxed:

fix(DropdownItem): pass innerProps to innerElement

---

CHANGELOG.md
package.json

1. Added default overlay components to embedded list tables
2. Added multistep progress bars
3. Modified FormPopover to accept an additional prop for footer content

chore(release): v 0.14.4

---

src/FormField.jsx
test/FormFieldSpec.jsx

add passed in dom attributes to the rendered control goup in form fields

feat(FormField): render dom attributes

---

CHANGELOG.md
package.json

chore(release): v 1.0.0
