demo/DemoPopoverSection.jsx
src/Popover.jsx
src/PopoverOverlay.jsx
test/PopoverOverlaySpec.jsx
test/PopoverSpec.jsx

Changes in this PR:
1. All users to override the offset of a popover
2. `target` can be a string ID or a function that returns the target element
3. `center` placement property. This will place the popover over the center of the target with no arrow rendered. This will be useful for modal like behavior where the popover should be placed over the center of the document body.

Popover improvements

---

src/PopoverFooter.jsx
test/PopoverFooterSpec.jsx

We need this in Reach because our tests expect the button group to have "save-cancel" on it, and more generally because all components should be able to have arbitrary extra classes where needed.

Allow additional classes on the popover footer

---

CHANGELOG.md
package.json

releasing version 0.5.0
1. Allow PopoverFooter to receive additional class names as a property

chore(release): v 0.5.0

---

demo/DemoPopover.jsx
src/Popover.jsx
test/PopoverSpec.jsx

Create the tether before the popover content is rendered, and manually trigger a tether reposition after the popover has been rendered. This fixes an issue where autofocused controls cause bad scrolling behavior; previously, the popover content would be initially rendered in the wrong place and then quickly repositioned, causing autofocus to scroll to the wrong place (typically, to the bottom of the page). This fixes that behavior and makes the popover component compatible with autofocus.

fix(popover): reposition popover after render

---

src/PopoverBody.jsx
test/PopoverBodySpec.jsx

Allow specification of additional popover body classNames via props. Previously there was no way to customize CSS classes on the body.

feat(PopoverBody): allow additional classNames on body

---

CHANGELOG.md
package.json

1. Allow PopoverBody to receive additional class names as a property.
2. Fixed an issue where autoFocus would cause popovers to scroll out of view

chore(release): v 0.6.0

---

src/ButtonGroup.jsx
src/PopoverBody.jsx
src/PopoverFooter.jsx
src/PopoverOverlay.jsx
src/StatusIndicator.jsx

Remove instances where 'children' is specified unnecessarily and 'className' is specified as an array rather than a string.

fix(propTypes): use accurate propTypes

---

CONTRIBUTING.md
Gruntfile.js
README.md
package.json
scripts/cibuild
scripts/server
scripts/setup
scripts/test
scripts/update

Added contributing guidelines.
Created scripts for running various development tasks that follow github's script guidelines for easier setup and development:
scripts/cibuild - runs lint, build, and test for CI server
scripts/server - starts an http server to serve up demo components; also watches for file changes
scripts/setup - installs all dependencies needed for development
scripts/test - starts karma to run unit tests; watches for file changes
scripts/update - can be run after pulling in master to get latest dependencies

Contributing Enhancements and Guidelines

---

CONTRIBUTING.md
demo/DemoActionMenu.jsx
demo/DemoPrimaryDropdown.jsx
demo/DemoUtilityDropdown.jsx
src/Dropdown.jsx
src/DropdownItem.jsx
src/DropdownTrigger.jsx
test/DropdownItemSpec.jsx
test/DropdownSpec.jsx
test/DropdownTriggerSpec.jsx

With the current implementation of dropdowns there is no way to hide the dropdown itself after clicking on an item of the dropdown. The desired behavior is that the dropdown should be hidden after it is clicked so a popover/navigation/some action can occur without the dropdown still being visible.

Make clicks on dropdown items close the dropdown

---

src/FacetsSection.jsx
test/FacetsSectionSpec.jsx

Perform a deep clone of the selectedCriteria prop, so the object referenced by the prop is not mutated
Fixes issue #78

fix(FacesSection): Clone selectedCriteria prop

---

demo/DemoButtonGroupSection.jsx
demo/DemoButtonSection.jsx
demo/DemoDropdownSection.jsx
demo/DemoPopover.jsx
src/Button.jsx
test/ButtonSpec.jsx

There are only three permissible types for an html button - 'submit',
'reset' and 'button'. Any other type is treated as a 'submit' type. This
leads to unexpected behavior when using a non-submit button inside a
form (Hitting enter triggers the onClick handler of the non-submit
button). The correct behavior would be to set the type to 'button' in
this case and to 'submit' only when the button is intended as the
primary button of a form.
The button's type can now be set independently of the button's
canonStyle.
This fixes #81

fix(Button): Fix HTML type of Button

---

CHANGELOG.md
package.json

Release Notes:
BREAKING CHANGE: Upgrading to support react ~0.14.0. No functions that are marked as deprecated in React ~0.14.0 are used in this release.

chore(release): v 0.9.0

---

src/Facet.jsx

this.props is null in IE and that may be what is causing the Facets to break.  It could be that the props in general are null, either way there's no need to route though 'this' when we have the props as a param. 
edit:
tested on IE9, it works!

fix(Facets): don't reference this.props in Facet constructor

---

demo/DemoDropdownSection.jsx
src/Dropdown.jsx
src/DropdownTrigger.jsx
test/DropdownSpec.jsx
test/DropdownTriggerSpec.jsx

Introduces prop tether with value of 'right' or 'left' (default 'left') to DropdownTrigger.
Value of 'right' will tether the dropdown menu to the right of the trigger.

feat: optional tether prop for DropdownTrigger

---

src/Popover.jsx
test/PopoverSpec.jsx

Noticed the container was getting an extra 'rs-popover' class every time its props updated.  Adding a check for the class so it won't be added if it already exists.

Fix(Popover) don't add rs-popover class if it already exists

---

src/Popover.jsx
test/PopoverSpec.jsx

Allow users to manually override all tether config options. This allows users to have better control over placement of popovers for special cases.
Resolves issue #77

feat(popover): Override tether config

---

CHANGELOG.md
package.json

1. New 'tether' prop for the 'Popover' component.
1.a. This prop allows a user to override all tether config options.
1.b. BREAKING CHANGE: 'offset' prop has been removed from 'Popover', and can now be set in the 'tether' config prop
2. Fix to not add the 'rs-popover' class if it already exists when rendering a popover

chore(release): v 0.11.0

---

src/Popover.jsx

render popover subtree into a container so it gets the context from its parent component
addresses issue #99

fix(popover): popover missing context from parent

---

CHANGELOG.md
package.json

1. Render 'Popover' subtree component into a container so it will receive the context from its parent.

chore(release): v 0.11.1

---

demo/DemoDetailSection.jsx
demo/DemoView.jsx
src/DetailItem.jsx
src/DetailItemKey.jsx
src/DetailItemValue.jsx
src/DetailList.jsx
src/index.js
test/DetailItemKeySpec.jsx
test/DetailItemSpec.jsx
test/DetailItemValueSpec.jsx
test/DetailListSpec.jsx

Added DetailList, DetailItem, DetailItemValue, DetailItemKey components
and their respective tests/demo. Will allow the use of these canon-react
components elsewhere.

feat(details components): add multiple new details components

---

demo/DemoForm.jsx
demo/DemoFormPopover.jsx
demo/DemoPopover.jsx
demo/DemoPopoverSection.jsx
demo/DemoView.jsx
src/DetailsSection.jsx
src/Form.jsx
src/FormField.jsx
src/FormFieldHelp.jsx
src/FormFieldValidationBlock.jsx
src/FormPopover.jsx
test/DetailsSectionSpec.jsx
test/FormFieldHelpSpec.jsx
test/FormFieldSpec.jsx
test/FormFieldValidationBlockSpec.jsx
test/FormPopoverSpec.jsx
test/FormSpec.jsx

Added Form, FormField, and related components to encapsulate Canon forms and form validation messages
Changes are based on the Apollo changes here, updated to Canon-React patterns: https://github.com/racker/apollo/pull/45/files
I've removed FormButton and related, since they reproduce button logic we already have in other places.

feat: added form and field components

---

src/index.js

Form, FormPopover, and other form-related components were missing from index.js. Adds them.

fix(form): export form and related components

---

demo/DemoFormPopover.jsx
demo/DemoPopoverSection.jsx
src/Form.jsx
src/FormPopover.jsx
test/FormPopoverSpec.jsx
test/FormSpec.jsx

as the FormPopover component consumes the Form component, exposing the rs-form-horizontal class as optional is critical in the case of top aligned field labels as documented in Canon

fix form: expose rs-form-horizontal as optional

---

CHANGELOG.md
package.json

1. Render `Tooltip` subtree component into a container so it will receive the context from its parent.

chore(release): v 0.13.2

---

demo/DemoPopoverSection.jsx
src/ErrorIndicator.jsx
src/FormPopover.jsx
test/ErrorIndicatorSpec.jsx
test/FormPopoverSpec.jsx

This PR introduces an ErrorIndicator component to be used in cases such as displaying errors on the FormPopover footer. Currently, the error is being displayed through a FormFieldValidationBlock below the button components. However, the Canon classes being used in that component are meaningless outside of a control group, so the error would display as plain black text and the positioning (being rendered below the buttons) would display the error beside of the buttons, widening the popover substantially.
Current (screenshot of code I'm developing within Reach consuming the FormPopover pattern) -
With changes (rendering error through ErrorIndicator component located above buttons) -
Canon does not have any patterns surrounding error text outside of tables and validation, so I have settled …

Fix FormPopover error display [ready]

---

src/FormPopover.jsx

Previously the target prop on the FormPopover component was defined as being a string. However, the Popover component being rendered by the FormPopover accepts either strings or functions as the target.
This PR changes the FormPopover component to reflect that, preventing the invalid PropType warning from being thrown when the FormPopover is being passed a function as the target (which is a valid means of consuming the Popover and should be reflected in the FormPopover as such).
This is a long explanation for a small change.

fix (FormPopover propType): fix FormPopover target prop declaration [ready]

---

demo/DemoPopoverSection.jsx
src/FormPopover.jsx
test/FormPopoverSpec.jsx

Extend FormPopover pattern to optionally render more controls in footer than solely Submit and Cancel. 
This is not an uncommon pattern as popovers can be used as a location to both edit and delete an entity (example from Reach) -
The popover pictured above exposes both edit functionality as well as disabling/delete functionality.
Screenshot of FormPopover demo -

feat (FormPopover): add optional additional controls to footer [ready]

---

src/Button.jsx
src/Criteria.jsx
src/DetailsSection.jsx
src/Dropdown.jsx
src/DropdownItem.jsx
src/DropdownTrigger.jsx
src/Facet.jsx
src/FacetToggler.jsx
src/FacetsSection.jsx
src/Popover.jsx
src/PopoverOverlay.jsx
src/ProcessingIndicator.jsx
src/ProgressBar.jsx
src/StatusIndicator.jsx
src/TooltipTrigger.jsx

Including -
- reduce duplication within components by evaluating conditional display of subcomponents inline
- ternary over if/else if logic flow is simple enough
- prefer arrow function over ```function ()```
- classname module utilization - if module is being used, use consistently for all classes on an element
- curly bracket spacing (can be a lint rule, mebbe in another PR) - spaces after opening brace and before closing brace - ```{ this.is.good }``` vs ```{this.is.ew}```
- proptype declaration - use Object.keys(WHAT_NOT) whenever possible to reduce duplication while retaining concise reference to accetable values
- var declaration via let vs const - const whenever possible, using let when something will be reassigned or edited
- binding functions in constructor - this should be done …

refactor (normalize styling): normalize use of classname module, other styling

---

demo/DemoForm.jsx
src/FormField.jsx
src/FormFieldValidationBlock.jsx
test/FormFieldSpec.jsx
test/FormFieldValidationBlockSpec.jsx

Allow users to pass an inlineValidation prop into a FormField component to make the validation be inline with the field contents.  Also allow the success prop to be a boolean or string, so that an empty message can be shown with the green check mark.

feat(FormField): Allow inline validation

---

src/Button.jsx

cibuild was failing on warnings due to keyless components being within arrays in the render of Button.jsx.

fix(Button): removing arrays with keyless components

---

demo/DemoListTableSection.jsx
src/EmbeddedListTable.jsx
src/ListTable.jsx
src/ListTableHeader.jsx
src/ListTableOverlaySelector.jsx
src/TextColumnHeader.jsx

SortDirection and OverlayStatus are mappings of key names (SortDirection.ASCENDING, frex) to values ('asc') so that a developer can use the key names to pass the values. Therefore, the PropTypes declaration should be validating on the value that would be passed, not the key name.

fix(List Table): Fix incorrect direction and overlay status proptype declarations

---

scripts/publish_new_release.py

This resolves a few bugs with the automation script that were due to the idiosyncratic setup I had locally. We don't need `sudo` to run the `cibuild` script, and since tar-ing the minified JS doesn't happen by default, that needs to happen within this script.

fix(automation): add tar zip step to release script

---

src/TooltipTrigger.jsx
test/TooltipTriggerSpec.jsx

Add a prop "onDisplay" which will be fired when the tooltip is shown, which works as a seam for adding tracking to tooltips.

feat(TooltipTrigger): Add onDisplay hook prop

---

src/EmbeddedListTable.jsx
test/EmbeddedListTableSpec.jsx

The List Table provides default overlay components, but the embedded list table did not.  Adding them here as well.

fix(Embedded List Table): Provide default overlay components

---

demo/DemoMultiStepProgressSection.jsx
demo/DemoView.jsx
src/ProgressBar.jsx
src/ProgressBarContainer.jsx
src/ProgressSegment.jsx
src/index.js
test/ProgressBarContainerSpec.jsx
test/ProgressSegmentSpec.jsx

I extracted some of the common functionality of the existing progress bar and multi step progress bar components into a ProgressSegment and ProgressBarContainer components.  The normal ProgressBar now uses these components and works the same, while multistep progress bars can be created by putting multiple segments into a container.

Add multistep progress components

---

.gitignore
demo/DemoPopoverSection.jsx
src/FormPopover.jsx
test/FormPopoverSpec.jsx

This PR adds a new prop to the `FormPopover` component in order to allow developers to display additional right-aligned with the control buttons/links (e.g. submit and cancel).
I have a submittable popover component using the `FormPopover` component and I need to display a right-aligned tooltip on the footer. There is no appropriate way to use a `FormPopover` and display additional content after the control buttons. The only thing similar is the `additionalControls` prop, but it is rendered before the cancel component.
1. Renamed the new prop from `additionalInfo` to `additionalFooterContent`
2. Always right-align the extra content (see screenshots below). The implementation is straightforward: wrap the content in a `<div />` with class `rs-pull-right` (tests updated accordingly).
3. …

Add optional prop to display additional content on the FormPopover footer

---

src/ListTableBody.jsx
src/ListTableRow.jsx
test/ListTableBodySpec.jsx

Imagine you're displaying the contents of a dictionary in a table. The table expects its data to be described as an array. This makes sense, but it's a bit inconvenient. For example, let's say you want the items in the dictionary to be displayed sorted by key. You would do something like this:
```
const sortedKeys = data.keys().sort();
const sortedObjects = sortedKeys.map((key) => data[key]);
return <ListTableBody collection={sortedObjects} keyGenerator={(instance, index) => sortedKeys[index])} />
```
And you have the data, piece of cake. But there's a problem: that resulting array doesn't have the key anymore!
No problem, you can put it back in:
```
const sortedKeys = data.keys().sort();
const sortedObjects = sortedKeys.map((key) => ({ dataId: key, data: data[key] }));
return …
```

feat(ListTableBody): make row key accessible to the row itself

---

CHANGELOG.md
package.json

1. Render passed in dom attributes on rendered control group in FormField component.

chore(release): v 0.14.5

---

CHANGELOG.md
package.json

1. Render passed in class names on the control group that is rendered by the FormField component.

chore(release): v 0.14.6
